version: '3.8'
services:
  redis:
    image: redis:7
    container_name: poc_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: poc_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1

  worker:
    build: .
    container_name: poc_worker
    command: celery -A poc_server worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1

